language: android
script: ./gradlew build assembleRelease
android:
  components:
  - build-tools-20.0.0
  - android-19

deploy:
  - provider: releases
    api_key:241f3444833c01a3e8de583ebeadeff37107c05c
    file: app/build/outputs/apk/app-release.apk
    on:
      repo: Zzivi/Sodexo
      tags: true

notifications:
  email:
    recipients:
    - waqascs@gmail.com
    - waqascs@gmail.com
    on_success: always
    on_failure: always
